<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Корзина");
?>
<?$APPLICATION->IncludeComponent(
	"bitrix:sale.basket.basket", 
	"main", 
	array(
		"COLUMNS_LIST" => array(
			0 => "NAME",
			1 => "DELETE",
			2 => "DELAY",
			3 => "PRICE",
			4 => "QUANTITY",
		),
		"OFFERS_PROPS" => array(
		),
		"PATH_TO_ORDER" => SITE_DIR."order/",
		"HIDE_COUPON" => "N",
		"PRICE_VAT_SHOW_VALUE" => "Y",
		"COUNT_DISCOUNT_4_ALL_QUANTITY" => "N",
		"USE_PREPAYMENT" => "N",
		"SET_TITLE" => "N",
		"AJAX_MODE_CUSTOM" => "Y",
		"SHOW_MEASURE" => "Y",
		"PICTURE_WIDTH" => "80",
		"PICTURE_HEIGHT" => "80",
		"SHOW_FULL_ORDER_BUTTON" => "Y",
		"SHOW_FAST_ORDER_BUTTON" => "Y",
		"COMPONENT_TEMPLATE" => "main",
		"QUANTITY_FLOAT" => "N",
		"ACTION_VARIABLE" => "action",
		"TEMPLATE_THEME" => "blue",
		"AUTO_CALCULATION" => "Y",
		"USE_GIFTS" => "Y",
		"GIFTS_BLOCK_TITLE" => "Выберите один из подарков",
		"GIFTS_HIDE_BLOCK_TITLE" => "N",
		"GIFTS_TEXT_LABEL_GIFT" => "Подарок",
		"GIFTS_PRODUCT_QUANTITY_VARIABLE" => "",
		"GIFTS_PRODUCT_PROPS_VARIABLE" => "prop",
		"GIFTS_SHOW_OLD_PRICE" => "N",
		"GIFTS_SHOW_DISCOUNT_PERCENT" => "Y",
		"GIFTS_SHOW_NAME" => "Y",
		"GIFTS_SHOW_IMAGE" => "Y",
		"GIFTS_MESS_BTN_BUY" => "Выбрать",
		"GIFTS_MESS_BTN_DETAIL" => "Подробнее",
		"GIFTS_PAGE_ELEMENT_COUNT" => "4",
		"GIFTS_CONVERT_CURRENCY" => "N",
		"GIFTS_HIDE_NOT_AVAILABLE" => "N"
	),
	false
);?>
<?$APPLICATION->IncludeComponent(
								"bitrix:catalog.bigdata.products", 
								"main", 
								array(
									"LINE_ELEMENT_COUNT" => "5",
									"TEMPLATE_THEME" => "blue",
									"DETAIL_URL" => "",
									"BASKET_URL" => SITE_DIR."basket/",
									"ACTION_VARIABLE" => "ACTION",
									"PRODUCT_ID_VARIABLE" => "ID",
									"PRODUCT_QUANTITY_VARIABLE" => $arParams["PRODUCT_QUANTITY_VARIABLE"],
									"ADD_PROPERTIES_TO_BASKET" => "N",
									"PRODUCT_PROPS_VARIABLE" => $arParams["PRODUCT_PROPS_VARIABLE"],
									"PARTIAL_PRODUCT_PROPERTIES" => "N",
									"SHOW_OLD_PRICE" => "Y",
									"SHOW_DISCOUNT_PERCENT" => "Y",
									"PRICE_CODE" => array(
										0 => "BASE",
									),
									"SHOW_PRICE_COUNT" => "1",
									"PRODUCT_SUBSCRIPTION" => "N",
									"PRICE_VAT_INCLUDE" => "N",
									"USE_PRODUCT_QUANTITY" => "N",
									"SHOW_NAME" => "Y",
									"SHOW_IMAGE" => "Y",
									"MESS_BTN_BUY" => "",
									"MESS_BTN_DETAIL" => "",
									"MESS_BTN_SUBSCRIBE" => "",
									"MESS_NOT_AVAILABLE" => $arParams["MESS_NOT_AVAILABLE"],
									"PAGE_ELEMENT_COUNT" => "20",
									"SHOW_FROM_SECTION" => "N",
									"IBLOCK_TYPE" => "aspro_mshop_catalog",
									"IBLOCK_ID" => "73",
									"DEPTH" => "2",
									"CACHE_TYPE" => "A",
									"CACHE_TIME" => "3600",
									"CACHE_GROUPS" => "N",
									"HIDE_NOT_AVAILABLE" => "Y",
									"CONVERT_CURRENCY" => "N",
									"CURRENCY_ID" => $arParams["CURRENCY_ID"],
									"SECTION_ID" => $arResult["VARIABLES"]["SECTION_ID"],
									"SECTION_CODE" => $arResult["VARIABLES"]["SECTION_CODE"],
									"SECTION_ELEMENT_ID" => $arResult["VARIABLES"]["SECTION_ID"],
									"SECTION_ELEMENT_CODE" => $arResult["VARIABLES"]["SECTION_CODE"],
									"ID" => "",
									"={\"PROPERTY_CODE_\".\$arParams[\"IBLOCK_ID\"]}" => $arParams["LIST_PROPERTY_CODE"],
									"={\"CART_PROPERTIES_\".\$arParams[\"IBLOCK_ID\"]}" => $arParams["PRODUCT_PROPERTIES"],
									"RCM_TYPE" => "bestsell",
									"={\"OFFER_TREE_PROPS_\".\$ElementOfferIblockID}" => $arParams["OFFER_TREE_PROPS"],
									"={\"ADDITIONAL_PICT_PROP_\".\$ElementOfferIblockID}" => $arParams["OFFER_ADD_PICT_PROP"],
									"COMPONENT_TEMPLATE" => "basket",
									"SHOW_PRODUCTS_73" => "Y",
									"PROPERTY_CODE_73" => array(
										0 => "",
										1 => "",
									),
									"CART_PROPERTIES_73" => array(
									),
									"ADDITIONAL_PICT_PROP_73" => "MORE_PHOTO",
									"LABEL_PROP_73" => "-",
									"USE_TITLE_BLOCK" => "Y",
									"DISPLAY_COMPARE" => "Y"
								),
								false
							);
							?><?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>