<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("");
?>
<p class="MsoNormal" style="outline: none; margin: 0px; padding: 0px; border: 0px; font-size: 14px; vertical-align: baseline; color: rgb(132, 130, 125); font-family: Arial, sans-serif; line-height: 24px;">Как у многих это бывает, идея <b style="outline: none; margin: 0px; padding: 0px; border: 0px; vertical-align: baseline; font-stretch: normal !important; line-height: normal !important;">создать что-то новое</b>, актуальное и современное приходит очень внезапно, и потом ты всегда удивляешься: «Как это я не осознал это раньше?». Так произошло и с Создателями <b style="outline: none; margin: 0px; padding: 0px; border: 0px; vertical-align: baseline; font-stretch: normal !important; line-height: normal !important;"><font color="#7c4900" style="outline: none;">«Просто КЛУБ БРИТВ»</font></b> в декабре 2012 года…</p>

<p class="MsoNormal" style="outline: none; margin: 0px; padding: 0px; border: 0px; font-size: 14px; vertical-align: baseline; color: rgb(132, 130, 125); font-family: Arial, sans-serif; line-height: 24px;">
  <br style="outline: none;" />
</p>

<p class="MsoNormal" style="outline: none; margin: 0px; padding: 0px; border: 0px; font-size: 14px; vertical-align: baseline; color: rgb(132, 130, 125); font-family: Arial, sans-serif; line-height: 24px;">Исторически сложилось, что Создатели этого проекта уже очень давно «вращались» в этом узко-потребительском рынке (конечно же, имеется в виду рынок влажного бритья), и за все это время они успели скопить достаточно сведений о направлениях и тенденциях развития этого потребительского сегмента. Если взглянуть поверхностно – что интересного в рынке влажного бритья? Какие тут могут быть современные идеи, тенденции и технологии? Да ничего: существует 2-3 крупнейших мировых производителя бритв, которые постепенно «усовершенствуют» свои бритвы, вкладывают невиданные суммы денег в рекламу и заставляют нас с вами покупать эти «навороченные» бритвы. При этом<b style="outline: none; margin: 0px; padding: 0px; border: 0px; vertical-align: baseline; font-stretch: normal !important; line-height: normal !important;">средняя стоимость бритвы растет от года к году</b>, и все больше людей начинают осознавать, что они <b style="outline: none; margin: 0px; padding: 0px; border: 0px; vertical-align: baseline; font-stretch: normal !important; line-height: normal !important;">сильно</b> (и это еще слабо сказано) <b style="outline: none; margin: 0px; padding: 0px; border: 0px; vertical-align: baseline; font-stretch: normal !important; line-height: normal !important;">переплачивают</b> за такой тривиальный продукт, как бритву!</p>
<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>